var path       = require('path')
  , fs         = require('fs')
  , browserify = require('browserify')
  , bundlePath = path.join("dist", "examples", 'minimal.js')

browserify({debug: true})
  .require(require.resolve('./minimal.js'), { entry: true })
  .external("../jam")
  .bundle()
  .on('error', function (err) { console.error(err); })
  .pipe(fs.createWriteStream(bundlePath))
